service:dyname-crud-api

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-west-1
  environment:
    DYNAMODN_TABLE_NAME: ${self:custom.postsTableName}

custom:
  postsTableName: posts-table-${self:provider.stage}

plugins:
  - serverless-iam-roles-per-function

functions:
  getPost:
    handler: api.getPost
    name: getPost
    memorySize: 128 #mb
    timeout: 5 # seconds
    events:
      - http:
          path: post/{postId}
          method: GET
          iamRoleStatements:
            - Effect: "Allow"
              Action:
                - "dynamodb:PutItem"
              Resource: !GetAtt PostsTable.Arn
  createPost:
    handler: api.createPost
    name: create-post
    memorySize:  128 #mb
    timeout: 5 # seconds
    events:
      - http:
          path: post
          method: POST
          iamRoleStatements:
            - Effect: "Allow"
              Action:
                - "dynamodb:PutItem"
              Resource: !GetAtt PostsTable.Arn
  updatePost:
    handler: api.updatePost
    name: update-post
    memorySize:  128 #mb
    timeout: 5 # seconds
    events:
      - http:
          path: post/{postId}
          method: PUT
          iamRoleStatements:
            - Effect: "Allow"
              Action:
                - "dynamodb:UpdateItem"
              Resource: !GetAtt PostsTable.Arn
  updatePost:
    handler: api.updatePost
    name: update-post
    memorySize:  128 #mb
    timeout: 5 # seconds
    events:
      - http:
          path: post/{postId}
          method: PUT
          iamRoleStatements:
            - Effect: "Allow"
              Action:
                - "dynamodb:UpdateItem"
              Resource: !GetAtt PostsTable.Arn

resources:
  Resources:
    PostTable:
      Type: AWS::DynameDb::Table
      Properties:
        TableName: ${self:custom.postsTableName}
        AttributesDefinations:
          - AttributeName: postId
            AttributeType: S
        KeySchema:
        - AttributeName: postId
          KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
